# Generated by Django 5.2.12 on 2026-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('openlibrary', 'Open Library'), ('manual', 'Manual')], default='openlibrary', max_length=50),
        ),
    ]
